services:
  db:
    image: mysql:8.0
    container_name: eoma_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: EoMApassword
      MYSQL_DATABASE: EoMA
    ports:
      - "3306:3306"
    volumes:
      - ./Database/EoMA_db.sql:/docker-entrypoint-initdb.d/EoMA_db.sql
    command: --default-authentication-plugin=mysql_native_password